[package]
name = "betrayal_engine"
version = "0.1.0"
authors = ["niedzwiedzw <niedzwiedzwo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
byteorder = "1.4.3"
nix = "0.20.0"
procfs = "0.9.1"
procmaps = "0.4.1"
thiserror = "1.0.24"
trickster = {git = "https://github.com/Niedzwiedzw/trickster"}
